# Generated by Django 5.0.6 on 2024-07-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='place',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
